# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__,"\n")
print(np.show_config())

1.19.5 

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
zer= np.zeros(10, dtype=int)
zer

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print("Size of the above array is",zer.size)
print("Length of an item in the above array is",zer.itemsize)

Size of the above array is 10
Length of an item in the above array is 8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

None


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
zer1= np.zeros(10, dtype=int)
zer1[4]=1
zer1

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
arr1 = np.arange(10,50)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
arr2 = np.arange(10,51,2)
arr2[::-1]

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
arr3 = np.arange(9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
arr4=np.array([1,2,0,0,4,0])
print ("Indices of non zero elements : ",np.nonzero(arr4))
#returns a tuple of arrays,one for each dimension of arr,containing the indices of the non-zero items in that dimension.

Indices of non zero elements :  (array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
arr5=np.eye(3, dtype=int)
arr5

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
arr6=np.random.random((3,3,3)) #Return random floats in the half-open interval [0.0, 1.0)
arr6

array([[[0.15121679, 0.38498692, 0.01849751],
        [0.60104712, 0.61692875, 0.17665   ],
        [0.38700879, 0.77187127, 0.83701382]],

       [[0.30304101, 0.51490109, 0.80675597],
        [0.45718323, 0.96928344, 0.48040902],
        [0.72058354, 0.32972243, 0.18581689]],

       [[0.57344667, 0.1551761 , 0.85171997],
        [0.8620901 , 0.46618819, 0.10366963],
        [0.02751411, 0.44787421, 0.4309447 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
arr7=np.random.random((10,10))
print("Minimum value in the array:",np.min(arr7))
print("Maximum value in the array:",np.max(arr7))

Minimum value in the array: 0.016718228786096967
Maximum value in the array: 0.9899910754309683


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
arr8=np.random.randint(10,100,size=30)
print(arr8)
print(f"Mean value = {np.mean(arr8)}")

[27 97 96 88 37 81 27 21 21 47 50 71 35 44 92 45 40 88 52 51 51 97 11 49
 17 64 92 66 44 13]
Mean value = 53.8


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
arr9=np.ones((4,4),dtype=int)
arr9[1:-1,1:-1]=0
arr9

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
arr10=np.arange(1,17).reshape(4,4)
arr10=np.pad(arr10, pad_width=1,mode="constant", constant_values=0)
arr10

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  0],
       [ 0,  9, 10, 11, 12,  0],
       [ 0, 13, 14, 15, 16,  0],
       [ 0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
arr11 = np.array([1,2,3,4])
np.diag(arr11,k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
arr12=np.zeros((8,8),dtype=int)
arr12[1::2,::2] = 1
arr12[::2,1::2] = 1
arr12

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
arr13=np.unravel_index(100,(6,7,8))
arr13

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a=np.array([[0,1],[1,0]])
arr14=np.tile(a,(4,4))
arr14

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
b=np.random.random((5,5))
b=(b-b.min())/(b.max()-b.min())
b

array([[0.09852028, 0.9576732 , 0.95186818, 0.7236101 , 0.27324069],
       [0.02605141, 0.07048669, 0.2143235 , 0.9734001 , 0.83134428],
       [0.85067244, 0.05161641, 0.66122015, 0.62855923, 0.2866382 ],
       [0.31898728, 0.1142975 , 0.        , 0.97041918, 0.90767494],
       [0.59071138, 0.29589308, 0.06614574, 1.        , 0.45891529]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a = np.arange(1,16).reshape((5, 3))
b = np.arange(1,7).reshape((3, 2))
np.dot(a,b)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
arr15 = np.arange(13)
arr15[(arr15 > 3) & (arr15 <= 8)] = -1
arr15

array([ 0,  1,  2,  3, -1, -1, -1, -1, -1,  9, 10, 11, 12])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(6) 
print(Z)
print(Z ** Z)       # = [0^0, 1^1, 2^2, 4^4, 5^5] = [1, 1, 4, 27, 256, 3125]
print(2 << Z >> 2)  # = [0, 1, 2, 4, 8, 16]
print(Z < - Z )     # = [False, False, False,False, False, False]
print(1j * Z  )     # = [0 + 0.j, 0 + 1.j, 0 + 2.j,v0.+3.j, 0.+4.j, 0.+5.j]
print(Z / 1 / 1)    # = [0., 1., 2., 3., 4., 5.]
print(Z < Z > Z  )

[0 1 2 3 4 5]
[   1    1    4   27  256 3125]
[ 0  1  2  4  8 16]
[False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[0. 1. 2. 3. 4. 5.]


ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
np.array([np.nan]).astype(int).astype(float)

nan
0


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([ 9., -5., -6., 10., -3., -1.,  7., -9., -2., -2.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.arange(1, 16)
y = np.arange(7, 20)
np.intersect1d(x,y)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [5]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)

np.errstate(divide='ignore')
Z = np.ones(1) / 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [2]:
np.sqrt(-1) == np.emath.sqrt(-1)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [7]:
today = np.datetime64('today', 'D')

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(today)
print(yesterday)
print(tomorrow)

2022-02-07
2022-02-06
2022-02-08


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [8]:
da = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
da

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [10]:
A = np.ones(3) * 2
B = np.ones(3) * 3
C = np.ones(3) * 5
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
A

array([-5., -5., -5.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [13]:
a = np.random.uniform(0,20,10)
print(a,"\n")
print(a - a%1)

print(np.floor(a))

print(np.ceil(a)-1)

print(a.astype(int))

print(np.trunc(a))

[14.17451192  2.96217375  6.49478069 11.15214621 17.62412212  8.35074112
  4.31199309 19.434509    0.53346127 16.33240732] 

[14.  2.  6. 11. 17.  8.  4. 19.  0. 16.]
[14.  2.  6. 11. 17.  8.  4. 19.  0. 16.]
[14.  2.  6. 11. 17.  8.  4. 19.  0. 16.]
[14  2  6 11 17  8  4 19  0 16]
[14.  2.  6. 11. 17.  8.  4. 19.  0. 16.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [17]:
x = np.zeros((5, 5),dtype=int)
x += np.arange(5)
x

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [18]:
def generate_integers():
    for i in range(10):
        yield i
x=np.fromiter(generate_integers(), dtype=np.float32, count=-1)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [21]:
y=np.linspace(0, 1,11, endpoint=False)[1:]
y

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [24]:
x = np.random.randint(20,45,size=10)
print("Before Sorting:\n\t",x)
x.sort()
print("After Sorting:\n\t",x)

Before Sorting:
	 [31 44 33 29 24 34 26 43 44 24]
After Sorting:
	 [24 24 26 29 31 33 34 43 44 44]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [25]:
a = np.arange(10)

np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [28]:
x = np.arange(20)
y = np.arange(20)
a1=np.array_equal(x, y)
print(a1)
a2= np.allclose(x,y)
print(a2)

True
True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [29]:
x = np.arange(10)
x.flags.writeable = False
x[1] = 1 

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [30]:

arr = np.random.random((10, 2))
x, y = arr[:, 0], arr[:, 1]
r = np.sqrt(x ** 2 + y ** 2)
o = np.arctan2(y, x) #Array of angles in radians
print(r)
print(o)

[0.83014446 0.7475338  0.71955416 0.5838383  0.36777921 0.86804098
 0.78770593 0.94657301 0.31714566 0.95304298]
[0.79291873 0.79385931 0.74663596 0.90781163 1.09683215 0.98190763
 1.19814205 1.21478962 0.56280368 0.04378072]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [35]:
x = np.random.random(10)
print("Before Replacement:\n\t",x)
x[np.argmax(x)]=0
print("\nAfter Replacement:\n\t",x)

Before Replacement:
	 [0.98478661 0.45871709 0.35880685 0.58754879 0.95621084 0.48169367
 0.46887213 0.05033201 0.74720038 0.88077649]

After Replacement:
	 [0.         0.45871709 0.35880685 0.58754879 0.95621084 0.48169367
 0.46887213 0.05033201 0.74720038 0.88077649]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [37]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [41]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))

c = 1 / np.subtract.outer(x, y)

np.linalg.det(c)

array([[-1.66586341e+03,  2.46963841e+04,  1.25069459e+04,
        -6.87631034e+06, -2.92660407e+04],
       [ 7.25629306e+03,  2.26404482e+05, -2.05569454e+03,
        -5.11485665e+05,  2.33971195e+04],
       [-3.52231128e+04,  8.48377110e+04, -8.30044938e+04,
         3.65069038e+04,  1.99740804e+05],
       [-6.54710256e+05, -2.68158874e+03,  1.39498278e+05,
        -3.87901972e+04, -2.37143405e+04],
       [ 9.66823658e+04, -7.12207329e+05,  1.86954387e+05,
         6.54047342e+03, -1.59992033e+05]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [44]:
for dtype in [np.int8, np.int32, np.int64]:

  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max,"\n")

for dtype in [np.float32, np.float64]:

  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps,"\n")


-128
127 

-2147483648
2147483647 

-9223372036854775808
9223372036854775807 

-3.4028235e+38
3.4028235e+38
1.1920929e-07 

-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16 



#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [45]:
np.set_printoptions()

d = np.zeros((16,16))

print(d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [46]:
x = np.arange(100)
print(x,"\n")
v = np.random.uniform(0,100)
print(v,"\n")
index = (np.abs(x-v)).argmin()

print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 

24.468200677998908 

24


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [47]:
m = np.zeros(10, [ ( 'position', [('x', float, 1),('y', float, 1)] ),('color', [ ('r', float, 1),('g', float, 1),('b', float, 1)])])

print(m)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [48]:
m = np.random.random((10,2))

x,y = np.atleast_2d(m[:,0], m[:,1])

d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)

print(d)

[[0.         0.84710302 0.67080973 0.9538176  0.39483142 0.09038574
  0.6273624  0.31761027 0.14760933 0.64997223]
 [0.84710302 0.         0.69539062 0.48198219 0.50595593 0.93473793
  1.01939079 0.75924987 0.98906344 0.23767062]
 [0.67080973 0.69539062 0.         0.42319108 0.68867116 0.70977413
  0.37231959 0.36274674 0.7952572  0.48158213]
 [0.9538176  0.48198219 0.42319108 0.         0.78206689 1.01951122
  0.79417786 0.70872081 1.09809791 0.40919844]
 [0.39483142 0.50595593 0.68867116 0.78206689 0.         0.48455097
  0.84176648 0.48866523 0.51690286 0.38383114]
 [0.09038574 0.93473793 0.70977413 1.01951122 0.48455097 0.
  0.6165066  0.34757895 0.08578214 0.73278649]
 [0.6273624  1.01939079 0.37231959 0.79417786 0.84176648 0.6165066
  0.         0.35664772 0.69429997 0.78528917]
 [0.31761027 0.75924987 0.36274674 0.70872081 0.48866523 0.34757895
  0.35664772 0.         0.4332813  0.5243208 ]
 [0.14760933 0.98906344 0.7952572  1.09809791 0.51690286 0.08578214
  0.69429997 0.433281

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [49]:
a = np.arange(10, dtype=np.int32)

a = a.astype(np.float32, copy=False)

print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [50]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5\n

6, , , 7, 8\n

, , 9,10,11\n""")

Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [52]:
a = np.arange(9).reshape(3,3)

for index, value in np.ndenumerate(a):
  print(index, value)
  
print()

for index in np.ndindex(a.shape):
  print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [53]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
std, mean = 1.0, 0.0
g = np.exp(-( (d-mean)**2 / ( 2.0 * std**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [54]:
p = 5
arr = np.zeros((10,10))
np.put(arr, np.random.choice(range(10*10), p, replace=False),1)
print(arr)

[[0. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [56]:
arr1 = np.random.rand(5, 10)
print(arr1,"\n")
#axis = 0 means along the column and axis = 1 means working along the row.
result = arr1 - arr1.mean(axis=1, keepdims=True)
print(result)


[[0.99911429 0.77252008 0.9515087  0.51164893 0.22601512 0.24877767
  0.29635169 0.81817272 0.03690635 0.94135822]
 [0.46120137 0.62418094 0.94164963 0.01019367 0.95213567 0.65961033
  0.41769109 0.25248658 0.24068712 0.49382896]
 [0.37267387 0.36824069 0.45093599 0.02558875 0.49620978 0.57543616
  0.82162937 0.75833253 0.70785458 0.11968949]
 [0.54644577 0.70927861 0.35398898 0.40594452 0.67009128 0.18095259
  0.70551954 0.31626237 0.9310901  0.62769729]
 [0.06050864 0.13868013 0.05157487 0.42799529 0.29167126 0.07918896
  0.00778529 0.75489951 0.74465558 0.00322219]] 

[[ 0.41887691  0.1922827   0.37127133 -0.06858845 -0.35422226 -0.33145971
  -0.28388568  0.23793534 -0.54333103  0.36112084]
 [-0.04416516  0.1188144   0.43628309 -0.49517286  0.44676914  0.15424379
  -0.08767545 -0.25287996 -0.26467941 -0.01153758]
 [-0.09698525 -0.10141843 -0.01872313 -0.44407037  0.02655066  0.10577704
   0.35197024  0.28867341  0.23819546 -0.34996963]
 [ 0.00171867  0.16455151 -0.19073812 -0.138782

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [57]:
arr2 = np.random.randint(1,15,(5,3))
print(arr2,"\n")

print(arr2[arr2[:,1].argsort()])

[[ 4  8  4]
 [ 3 10 12]
 [ 8 11  3]
 [12 11 13]
 [ 4 12 13]] 

[[ 4  8  4]
 [ 3 10 12]
 [ 8 11  3]
 [12 11 13]
 [ 4 12 13]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [59]:
arr2 = np.random.randint(0,5,(5,5))
print(arr2,"\n")
print("Does the 2D array have null columns?")
print((~arr2.any(axis=0)).any())

[[3 1 2 3 0]
 [2 3 4 4 0]
 [2 2 4 3 3]
 [2 0 3 2 0]
 [1 1 4 2 0]] 

Does the 2D array have null columns?
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [60]:
m = np.random.uniform(0,1,10)
print(m,"\n")
n = 0.5
z=np.abs(m - n).argmin()
k = m.flat[z]
print(k)

[0.29070925 0.85037866 0.0699196  0.80262962 0.2461276  0.08440609
 0.5417372  0.43011469 0.96546606 0.87528561] 

0.541737195437996


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [61]:
a = np.arange(3).reshape(3,1)
b = np.arange(3).reshape(1,3)

it = np.nditer([a,b,None])
for x,y,z in it:
  z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [63]:
x = np.ones(10)
i = np.random.randint(0,len(x),20)
x += np.bincount(i, minlength=len(x))
print(x)

[4. 4. 2. 3. 2. 2. 2. 3. 3. 5.]


In [64]:
np.add.at(x, i, 1)
print(x)

[7. 7. 3. 5. 3. 3. 3. 5. 5. 9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [65]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [66]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [69]:
x = np.random.randint(0,10,(3,4,3,4))
sum = x.sum(axis=(-2,-1))
print(sum,"\n")
sum = x.reshape(x.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[50 73 69 61]
 [47 67 40 59]
 [50 66 59 55]] 

[[50 73 69 61]
 [47 67 40 59]
 [50 66 59 55]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [70]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.5422902  0.60186416 0.50462632 0.59120892 0.59828246 0.49683707
 0.52016266 0.59395587 0.44527742 0.46958675]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [71]:
x = np.random.uniform(0,3,(5,5))
y = np.random.uniform(0,3,(5,5))
np.diag(np.dot(x, y))

array([ 6.09680156, 15.47556937,  5.39542954,  7.14127999,  5.60903172])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [72]:
arr = np.array([1,2,3,4,5])
num_zer = 3
arr1 = np.zeros(len(arr) + (len(arr)-1)*(num_zer))
arr1[ : : num_zer+1 ] = arr
print(arr1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [73]:
x = 4*np.ones((5,5,3))
y = 2*np.ones((5,5))
print(x * y[:,:,None])

[[[8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]]

 [[8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]]

 [[8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]]

 [[8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]]

 [[8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]
  [8. 8. 8.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [76]:
ar = np.arange(30).reshape(5,6)
print("Before Swapping:\n")
print(ar)
ar[[0,1]] = ar[[1,0]]
print("\nAfter Swapping:\n")
print(ar)

Before Swapping:

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

After Swapping:

[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [77]:
C = np.bincount([1,1,2,3,4,4,6])

A = np.repeat(np.arange(len(C)), C)

print(A)


[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [78]:
def moving_average(a, n=3) :

  ret = np.cumsum(a, dtype=float)

  ret[n:] = ret[n:] - ret[:-n]

  return ret[n - 1:] / n

ar = np.arange(20)

print(moving_average(ar, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [79]:
from numpy.lib import stride_tricks

def rolling(a, window):

  shape = (a.size - window + 1, window)

  strides = (a.itemsize, a.itemsize)

  return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)

print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [80]:
Z = np.random.randint(0,2,100)

np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)

np.negative(Z, out=Z)

array([ 0.72590587,  0.50833053, -0.61627608,  0.17236407,  0.37052773,
       -0.50819285,  0.47110172, -0.09622261,  0.87441612,  0.26605958,
       -0.17470505,  0.17362164, -0.62834508,  0.50677304,  0.51122165,
       -0.32436088,  0.19794881, -0.97983058, -0.34250852,  0.1004316 ,
        0.69954795,  0.03725707,  0.02180975, -0.53811689,  0.93031425,
        0.71217851,  0.24364129, -0.3933507 , -0.42838967, -0.93305403,
        0.71826885, -0.61048824, -0.8745637 , -0.69601304,  0.64232656,
        0.24725243,  0.64763671, -0.05376361,  0.11845839,  0.41923888,
       -0.89645622,  0.1244464 ,  0.91803277, -0.35125582,  0.27501657,
        0.0465194 ,  0.03753113,  0.66269269,  0.64317517,  0.021598  ,
       -0.30427376, -0.44871929, -0.71149226, -0.27569403,  0.03818379,
        0.53732248,  0.94388822,  0.97358417, -0.76348039, -0.92868466,
        0.63282332,  0.77950246,  0.98485469, -0.74656725,  0.21340997,
        0.47210323, -0.07109708, -0.05643687, -0.71765726,  0.51

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [81]:
def distance(P0, P1, p):

  T = P1 - P0
  L = (T**2).sum(axis=1)
  U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
  U = U.reshape(len(U),1)
  D = P0 + U*T - p
  return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[8.25566172 8.38185093 3.40874982 2.96133735 4.43013977 4.57361945
 4.00247083 1.44476489 2.98201135 9.89634287]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [82]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.298421    4.80039647  2.53731382  6.53110496  1.02467551  5.85387966
   3.40371316  2.30568981  5.57138049  9.50688659]
 [ 4.56668749  0.78445876  6.09119476  0.25726063  1.83003326  9.49019108
   0.13464925  5.86277671  3.53537916 11.41255098]
 [ 9.01868413  2.99217169  9.6779473   1.20212397  0.89177595  7.10600282
   4.22479842  6.48413474  6.23661934  8.32335101]
 [14.60748848  5.902717   14.06285531  2.55110567  4.4325315   3.97869261
   9.71807288  7.0923908   9.47979747  4.33492918]
 [16.65511103 15.47297335  8.47281489 13.00133598 13.30689534  5.37917662
  12.99323325  3.18576657  1.63101792  3.87585606]
 [ 5.57388933  2.19631193  6.13052071  1.53920855  0.40130885  8.06972085
   0.98707333  4.87668897  3.17690892  9.98950278]
 [ 4.26906374  6.19484565  1.14787132  6.70113423  2.94025471  4.28232005
   0.39908396  1.04201491  2.55161683  7.20772301]
 [ 5.49831549 12.48123632  2.66589264 13.60819168  8.74991172  1.85800166
   2.44559498  7.88044884  7.83847143  1.8490893 ]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [83]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [84]:
arr = np.random.uniform(0,1,(10,10))
x, y, z = np.linalg.svd(arr) # Singular Value Decomposition
rank = np.sum(y > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [85]:
arr = np.random.randint(0,10,50)
print(arr,"\n")
print(np.bincount(arr).argmax())

[0 8 1 1 5 7 5 8 0 1 6 9 0 2 6 4 7 7 1 5 4 0 2 0 2 1 1 5 4 5 4 0 1 8 8 7 7
 8 7 9 7 8 4 1 3 9 8 7 1 5] 

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [86]:
arr = np.random.randint(0,5,(10,10))
print(arr,"\n")
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
result = stride_tricks.as_strided(arr, shape=(i, j, n, n), strides=arr.strides + arr.strides)
print(result)

[[3 1 3 1 2 3 2 4 3 2]
 [2 2 0 0 2 3 3 1 1 0]
 [1 2 3 4 0 0 4 1 4 0]
 [4 4 2 4 4 4 0 4 2 3]
 [2 3 3 2 3 0 4 4 1 1]
 [1 0 3 2 4 1 0 3 4 0]
 [2 2 2 4 4 0 4 0 1 4]
 [0 0 1 2 2 0 1 3 2 3]
 [1 2 1 2 2 0 2 4 0 1]
 [0 4 3 4 4 3 3 2 2 4]] 

[[[[3 1 3]
   [2 2 0]
   [1 2 3]]

  [[1 3 1]
   [2 0 0]
   [2 3 4]]

  [[3 1 2]
   [0 0 2]
   [3 4 0]]

  [[1 2 3]
   [0 2 3]
   [4 0 0]]

  [[2 3 2]
   [2 3 3]
   [0 0 4]]

  [[3 2 4]
   [3 3 1]
   [0 4 1]]

  [[2 4 3]
   [3 1 1]
   [4 1 4]]

  [[4 3 2]
   [1 1 0]
   [1 4 0]]]


 [[[2 2 0]
   [1 2 3]
   [4 4 2]]

  [[2 0 0]
   [2 3 4]
   [4 2 4]]

  [[0 0 2]
   [3 4 0]
   [2 4 4]]

  [[0 2 3]
   [4 0 0]
   [4 4 4]]

  [[2 3 3]
   [0 0 4]
   [4 4 0]]

  [[3 3 1]
   [0 4 1]
   [4 0 4]]

  [[3 1 1]
   [4 1 4]
   [0 4 2]]

  [[1 1 0]
   [1 4 0]
   [4 2 3]]]


 [[[1 2 3]
   [4 4 2]
   [2 3 3]]

  [[2 3 4]
   [4 2 4]
   [3 3 2]]

  [[3 4 0]
   [2 4 4]
   [3 2 3]]

  [[4 0 0]
   [4 4 4]
   [2 3 0]]

  [[0 0 4]
   [4 4 0]
   [3 0 4]]

  [[0 4 1]
   [4 0 4]
   [0 

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [92]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  9 16  9 10]
 [ 9  5 12  8 13]
 [16 12  5 42  2]
 [ 9  8 42  4  8]
 [10 13  2  8  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [87]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [88]:
arr = np.ones((16,16))
n = 4
s = np.add.reduceat(np.add.reduceat(arr, np.arange(0, arr.shape[0], n), axis=0),np.arange(0, arr.shape[1], n), axis=1)
print(s)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [89]:
arr = np.arange(10000)
np.random.shuffle(arr)
n = 5

# Slow
print (arr[np.argsort(arr)[-n:]])

[9995 9996 9997 9998 9999]


In [ ]:
# Fast
print (arr[np.argpartition(-arr,n)[:n]])

[9996 9999 9997 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [91]:
def cartesian(arrays):

  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)
  ix = np.indices(shape, dtype=int)
  ix = ix.reshape(len(arrays), -1).T
  for n, arr in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]
  return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [90]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
names='col1, col2, col3',
formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [93]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.58 s per loop
10 loops, best of 5: 141 ms per loop
10 loops, best of 5: 117 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [94]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


[0 1 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [98]:
arr1 = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
binary = ((arr1.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(binary[:,::-1],"\n")

arr2 = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(arr2[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]] 

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [100]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ,"\n")
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]] 

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [105]:
arr1 = np.random.uniform(0,5,10)
arr2 = np.random.uniform(0,5,10)

np.einsum('i->', arr1)    
np.einsum('i,i->i', arr1, arr2) 
np.einsum('i,i',arr1, arr2)   
np.einsum('i,j->ij',arr1, arr2)    

array([[ 0.39616993,  2.41033565,  6.31820296,  6.6409399 ,  9.13102518,
        11.47785665, 15.55428024,  2.18607669,  3.81850214,  6.06483372],
       [ 0.29714695,  1.80787037,  4.73896318,  4.98103177,  6.84871828,
         8.60895739, 11.66647571,  1.63966511,  2.86406454,  4.54892378],
       [ 0.0594092 ,  0.36145122,  0.94747059,  0.99586786,  1.36927824,
         1.72120644,  2.33250232,  0.32782159,  0.57261827,  0.90947562],
       [ 0.15298995,  0.93080544,  2.43991649,  2.56454863,  3.52615119,
         4.43243306,  6.00663592,  0.84420279,  1.47460067,  2.34207225],
       [ 0.17449152,  1.06162303,  2.78282811,  2.92497635,  4.0217248 ,
         5.05537766,  6.8508227 ,  0.96284904,  1.68184453,  2.67123261],
       [ 0.50081   ,  3.04697584,  7.98702527,  8.39500648, 11.54279616,
        14.5094945 , 19.66262086,  2.76348352,  4.82708031,  7.6667338 ],
       [ 0.29359613,  1.78626687,  4.68233402,  4.92150996,  6.76687819,
         8.50608297, 11.52706488,  1.62007161

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [106]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [107]:
X = np.random.randn(100)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.30089287  0.08389643]
